export const ACTIVITES_ACCUEILLANTES: string[] = [
  'Mairie',
  'Guichet france services',
  'Bibliothèque médiathèque',
  'Point justice',
  'Bureau de poste',
  'Administration publique',
  'Collectivité territoriale',
  'Maison de services au public',
  'Commissariat de Police',
  "Agence départementale d'information sur le logement",
  "Caisse d'allocations familiales (caf)",
  'Sécurité sociale, mutuelle santé',
  'Centre des finances publiques',
  'Emploi, formation',
  'Point information jeunesse',
  'Institut de formation, de recherche',
  'Centre d’information et d’orientation',
  "Centre d'information et d'orientation",
  "Mission locale pour l'insertion professionnelle et sociale des jeunes",
  'Association',
  'Centre social',
  "Centre de ressources et d'information",
  'Centre de protection maternelle et infantile (pmi)',
  "Point d'information local dédié aux personnes âgées",
  'Point conseil budget',
  "Centre d'information sur les droits des femmes et des familles",
  'Autres établissements pour adultes et familles en difficulté',
  'Ehpad',
  'Résidence, foyer',
  'Coworking',
  'Espace collaboratif',
  'Point accueil numerique',
  'Office de tourisme',
  'Salle des fêtes',
  'Centre culturel',
  'Théâtre',
  'Cinéma',
  'Musée',
  'Librairie',
  'Lycée',
  'Collège',
  'École primaire (regroupement maternelle et élémentaire)',
  'École élémentaire',
  'Stade',
  'Sports et loisirs',
  'Centre de loisirs',
  'Piscine, centre aquatique',
  'Ecole de danse'
];
