---
name: Transform and publish

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-to-data-gouv:
    name: Publish to data.gouv
    strategy:
      matrix:
        source: [
            hinaura,
            maine-et-loire,
            les-assembleurs,
            france-services,
            france-tiers-lieux,
            conseiller-numerique,
            francil-in,
            angers,
            hub-lo,
            mulhouse,
            data-inclusion,
            paca,
            loire-atlantique,
            rhin-occ,
            res-in,
            # les-landes,
            la-creuse,
            numi,
            vendee,
            ultra-num,
            haute-vienne,
            fibre-64,
            mednum-hub-antilles,
            gironde,
            etapes-numerique,
            charente-maritime,
            eure-et-loir,
            conumm
          ]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout mednum-cli repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Transform
        run: yarn transformer.${{ matrix.source }}

      - name: 'Create env file'
        run: |
          touch .env
          echo DATA_GOUV_API_URL="${{ secrets.DATA_GOUV_API_URL }}" >> .env
          echo DATA_GOUV_API_KEY="${{ secrets.DATA_GOUV_API_KEY }}" >> .env
          echo DATA_GOUV_REFERENCE_ID="${{ secrets.DATA_GOUV_REFERENCE_ID }}" >> .env
          echo DATA_GOUV_REFERENCE_TYPE="${{ secrets.DATA_GOUV_REFERENCE_TYPE }}" >> .env

      - name: Publish
        run: yarn publier.${{ matrix.source }}

  build:
    uses: romain-cambonie/serenity-workflows/.github/workflows/_build-and-upload-artifact.reusable.yml@master

  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout mednum-cli repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: bundle

      - name: Link the semantic release config and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          ln -s .tooling/.semantic-release/.semantic-release.config.cjs release.config.cjs
          ln -s .tooling/.semantic-release/.npmignore .npmignore
          npx semantic-release

  deduplicate:
    name: Publish data-inclusion without duplicates
    runs-on: ubuntu-latest
    environment: production
    needs:
      - publish-to-data-gouv

    steps:
      - name: Checkout client-application repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Deduplicate
        run: yarn dedupliquer.data-inclusion

      - name: 'Create env file'
        run: |
          touch .env
          echo DATA_GOUV_API_URL="${{ secrets.DATA_GOUV_API_URL }}" >> .env
          echo DATA_GOUV_API_KEY="${{ secrets.DATA_GOUV_API_KEY }}" >> .env
          echo DATA_GOUV_REFERENCE_ID="${{ secrets.DATA_GOUV_REFERENCE_ID }}" >> .env
          echo DATA_GOUV_REFERENCE_TYPE="${{ secrets.DATA_GOUV_REFERENCE_TYPE }}" >> .env

      - name: Publish
        run: yarn publier.data-inclusion
